# Comprehensive TAGS list
TAGS = [
    '2fa key',
    '64-hex characters',
    'BIP-39',
    'HD wallet',
    'MPC key share',
    'Secret Recovery Phrase',
    'api key',
    'authenticator backup',
    'backup file',
    'binance',
    'bip39',
    'bip44',
    'bitcoin',
    'blockchain',
    'cold wallet',
    'coinbase',
    'crypto password',
    'metamask vault',
    'mnemonic',
    'ledger',
    'trezor',
    'seed phrase',
    'private key',
    'wallet backup',
    'exodus',
    'trust wallet',
    'vault decryptor',
    'tarjeta',
    'cartao',
    'Write These Down In Order',
    'разбитый',
    'KREDI KARTI',
    'gift card code',
    # Add file extension variations
    '.txt',
    '.json',
    '.docx',
    '.jpg',
    '.pdf',
    '.zip',
    # Additional Terms
    # Add any additional terms or variations needed...
]